# Title: 
#     Ontology Title Required
# Constraint Description: 
#     Any owl:Ontology must have an rdfs:label.
# Severity:
#     Warning

PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?ontology ?warning
WHERE {
  ?ontology a owl:Ontology .
  FILTER NOT EXISTS { ?ontology rdfs:label ?label }

  BIND(CONCAT(
    "WARNING: This owl:Ontology has no rdfs:label — ",
    STR(?ontology)
  ) AS ?warning)
}
ORDER BY ?ontology