# .github/workflows/project2-tests.yml
name: Autograde Project 2

on:
  push:
    paths:
      - "projects/project-2/**"
      - ".github/workflows/project2-tests.yml"
  pull_request:
    paths:
      - "projects/project-2/**"
      - ".github/workflows/project2-tests.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: projects/project-2/assignment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug paths
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "Repo root:"
          ls -la "$GITHUB_WORKSPACE"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q
